name: Manual Deploy
env:
  CI: true
  FORCE_COLOR: 1

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Target Location'
        required: true
        type: choice
        default: 'eu-central-1'
        options:
          - eu-central-1
      # environment:
      #   description: 'Target Environment'
      #   required: true
      #   type: choice
      #   default: 'Staging'
      #   options:
      #     - Development
      #     - Staging
      #     - Production
jobs:
  terraform:
    uses: './.github/workflows/reusable-terraform.yml'
    with:
      location: ${{ inputs.location }}
    secrets: inherit