name: 🧪 Manually deploy tag to a environment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        default: 'v2.0.0'
        required: true
      env:
        description: 'Environment to deploy to'
        type: choice
        options:
          - development
          - testing
          - staging
          - production
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
    steps:
      - shell: bash
        run: echo "${{ github.event.inputs.tag }}"
      - uses: ./.github/workflows/reusable-deploy
        with:
          deployment-token: secrets.DEPLOYMENT_TOKEN
          github-token: secrets.GITHUB_TOKEN
          ref: ${{ github.event.inputs.tag }}
