name: 🧪 Manually deploy tag to a environment

on:
  workflow_dispatch:
    inputs:
      
      target-tag:
        description: 'Tag to deploy'
        default: 'v2.0.0'
        required: true
      target-env:
        description: 'Environment to deploy to'
        type: choice
        options:
          - development
          - testing
          - staging
          - production
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.target-env }}
    steps:
      - shell: bash
        run: echo ${{ github.event.ref }}
      - shell: bash
        run: echo ${{ github.event.inputs.target-tag }}
      - shell: bash
        run: echo ${{ github.event.inputs.target-env }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target-tag }}
      - uses: ./.github/actions/deploy-swa
        with:
          deployment-token: secrets.DEPLOYMENT_TOKEN
          github-token: secrets.GITHUB_TOKEN
          ref: ${{ github.event.inputs.target-tag }}
