name: 🧪 Manually deploy tag to a environment

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Environment to use"
        type: choice
        options:
          - development
          - testing
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.target-env }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: echo ${{ github.ref }}
      - shell: bash
        run: echo ${{ github.event.inputs.target-env }}

      - uses: ./.github/actions/deploy-swa
        with:
          deployment-token: secrets.DEPLOYMENT_TOKEN
          github-token: secrets.GITHUB_TOKEN
          ref: github.event.ref