name: Manual Deploy
env:
  CI: true
  FORCE_COLOR: 1

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Target Location'
        required: true
        type: choice
        default: 'eu-central-1'
        options:
          - eu-central-1
    environment:
      type: environment
jobs:
  terraform:
    uses: './.github/workflows/reusable-terraform.yml'
    with:
      environment: ${{ github.event.inputs.environment }}
      location: ${{ github.event.inputs.location }}
    secrets: inherit