name: 🚧 Push on "pull_request"

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-swa
        with:
          deployment-token: ${{ secrets.DEPLOYMENT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
