name: Deploy Azure Static Web App

on:
  workflow_call:
    inputs:
      github-token:
        description: GitHub Token
        type: string
        required: true
      deployment-token:
        description: Azure Static Web App Deployment Token
        type: string
        required: true
      env:
        description: Target env
        type: string
        required: false
      tag:
        description: Target tag
        type: string
        required: false

jobs:
  reusable_deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: ls
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - shell: bash
        run: ls
      # - if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
      #   name: Build And Deploy
      #   id: builddeploy
      #   shell: bash
      #   run: echo "Deploy - TO:${{ github.event.inputs.env }}"
      # - if: github.event_name == 'pull_request' && github.event.action == 'closed'
      #   name: Close Pull Request
      #   id: closepullrequest
      #   shell: bash
